version: "3"

services:

  project_learn_ros:
    build: ./
    network_mode: "host"
    tty: true
    volumes:
      - ./:/home/learn_ros
      - /tmp/.X11-unix:/tmp.X11-unix
    environment:
      - DISPLAY=$DISPLAY
