version: "3"

services:

  project-ros2-crazyswam2:
    build: ./
    network_mode: "host"
    tty: true
    volumes:
      - ./:/home/learn_ros/ws
      - /tmp/.X11-unix:/tmp.X11-unix
    environment:
      - DISPLAY=$DISPLAY
